// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package domain

import (
	"time"

	uuid "github.com/gofrs/uuid/v5"
)

type Alert struct {
	ID         int32
	ExternalID uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Message    string
}
