// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package domain

import (
	"context"

	uuid "github.com/gofrs/uuid/v5"
)

type Querier interface {
	CreateAlert(ctx context.Context, arg CreateAlertParams) (*Alert, error)
	DeleteAlertByID(ctx context.Context, id int32) error
	GetAlertByExternalID(ctx context.Context, externalID uuid.UUID) (*Alert, error)
	UpdateAlertByID(ctx context.Context, arg UpdateAlertByIDParams) (*Alert, error)
}

var _ Querier = (*Queries)(nil)
