name: "alert-service"

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: alert_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5440:5432"
    restart: unless-stopped
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "alert_service" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s